# Generated by Django 2.2.3 on 2020-03-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerhq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(default='', max_length=128)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
